# Generated by Django 4.0.3 on 2022-04-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.CharField(default='', max_length=16)),
                ('role_name', models.CharField(default=' ', max_length=100)),
                ('role_description', models.TextField()),
                ('role_access', models.CharField(default=' ', max_length=100)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
